server:
  port: 8095

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bars
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  http:
    encoding:
      charset: UTF-8
      enabled: true
flyway:
  baselineOnMigrate: true
  locations: db/migrations
